{
 "title": "Mac Stats",
 "description": "Dashboard for monitoring MacBook performance metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(avg_over_time({job=\"macbook_stats\"} | json | unwrap\n     cpu_usage_percent [$__interval]))",
     "legendFormat": "CPU Usage (%)",
     "query": "avg_over_time({job=\"macbook_stats\"} | json | unwrap cpu_usage_percent [$__interval])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(avg_over_time({job=\"macbook_stats\"} | json | unwrap memory_free_percent [$__interval]))",
     "legendFormat": "Memory Free (%)",
     "query": "avg_over_time({job=\"macbook_stats\"} | json | unwrap memory_free_percent [$__interval])"
    }
   ]
  },
  {
   "title": "Battery Percentage",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"macbook_stats\"} | json | unwrap battery_percentage [$__interval]) by (power_source)",
     "legendFormat": "{{power_source}}",
     "query": "avg_over_time({job=\"macbook_stats\"} | json | unwrap battery_percentage [$__interval]) by (power_source)"
    }
   ]
  }
 ]
}