[project]
name = "log-processing"
version = "0.1.0"
description = "A project to learn about Loki, Promtail and Grafana."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.5.0",
    "loki-logging-handler>=0.0.5",
    "pyloki>=0.2.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "requests>=2.28.2",
]
