[project]
name = "fastapi-basic"
version = "0.1.0"
description = "A minimal, tested FastAPI server implementing all HTTP methods."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anyio==3.7.1",
    "fastapi>=0.115.14",
    "pydantic>=2.11.7",
    "uvicorn>=0.30.3",
    "python-dotenv>=0.21.0",
    "sqlmodel>=0.0.19",

    "httpx>=0.28.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "psutil>=7.0.0",
    "typer>=0.16.0",
    "mypy>=1.10.0",
]
