[project]
name = "dashboard"
version = "0.1.0"
description = "A dashboard made with MonsterUI (official demo, minor modifications)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "monsterui>=1.0.21",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
]

[tool.setuptools]
py-modules = ["dashboard"]

[tool.ruff]
lint.per-file-ignores = { "dashboard.py" = ["F403", "F405"] }
