name: App Runner End-to-End Test

on:
  workflow_dispatch: # Allows manual triggering

# These permissions are required for the OIDC flow
permissions:
  id-token: write
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629215267253:role/GitHubActionsRole # Role ARN from the aws-github-oidc terraform output
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Run End-to-End Test
        run: make e2e ENV=e2e-test
        working-directory: ./aws-apprunner
